### ISSUE TITLE
navigate bar got stuck in bash guide page

### ISSUE THREAD

**Issue by haolian9** [TheAlternativeZurich/feedback#62]
hi, i'm not sure if i supposed to report things about https://thealternative.ch website here. if not, i'm sorry to do this.

the page i mentioned is https://thealternative.ch/guides/bash.php, its left `<nav>` keeps sticking,  reader can not scroll it. tht's said if the bottom line is "6 Tests and Conditionals", i can not see the rest TOC if i not scroll the whole page down.
i hope i made myself clear, but if you try to scroll the page, you will know it.

![6723c6d0-3a1e-11ed-acc0-b881989529be](https://user-images.githubusercontent.com/6236829/191645145-a6d60bb2-69c4-4a30-a3ca-a9eb2b9daef4.jpg)

**Comment by haolian9** [comment]
oh, i'm using vivaldi browser on archlinux.

**Comment by famoser** [comment]
Source code of the webpage is here: https://gitlab.ethz.ch/thealternative/website If you are from ETH, you should be able to access it.

I can reproduce this behavior; but do not really see a straightforward way to fix it. Feel free to try it yourself; else maybe at one of the Stammtische someone can take a look :) Next dates are here: https://thealternative.ch/

**Comment by famoser** [comment]
If you have additional infos / concerns the discussion is better moved here: https://gitlab.ethz.ch/thealternative/website/-/issues/16
Thank you for the report!
